### ISSUE TITLE
Scripts are not working after git clone

### ISSUE THREAD

**Issue by btamas** [AnastasiaArcadia/OATTest#1]
https://github.com/AnastasiaArcadia/OATTest/blob/ec643c4bbb4f9891cda6d0954ba3b53387171b12/package.json#L30

```
> test-project/node_modules/.bin/react-scripts start

sh: test-project/node_modules/.bin/react-scripts: No such file or directory
```

Proposed modification in `package.json`:
```json
"scripts": {
  "start": "react-scripts start",
  "build": "react-scripts build",
  "test": "react-scripts test",
  "eject": "react-scripts eject"
},
```

**Comment by AnastasiaArcadia** [comment]
Sorry, it's a mistake
Fixed in https://github.com/AnastasiaArcadia/OATTest/commit/b6071a615eafbfe9b7f358c4375fcbd0697358b8
